{% set version = "1.5" %}

package:
  name: webcolors
  version: {{ version }}

source:
  fn: webcolors-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/w/webcolors/webcolors-{{ version }}.tar.gz
  sha256: b3b1c3a41e9c69d1982b76b6531239115519f91cc034a24e975749832dc51b8e

build:
  number: 2
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - webcolors

about:
  home: https://github.com/ubernostrum/webcolors
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Library for working with HTML/CSS color formats in Python.

extra:
  recipe-maintainers:
    - jakirkham
