{% set version = "1.9" %}

package:
  name: webcolors
  version: {{ version }}

source:
  fn: webcolors-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/w/webcolors/webcolors-{{ version }}.tar.gz
  sha256: ad54b6c1e524a492506232b7cea757367a5535e22db09e998e7b056a16b198bc

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - webcolors

about:
  home: https://github.com/ubernostrum/webcolors
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Library for working with HTML/CSS color formats in Python.

extra:
  recipe-maintainers:
    - jakirkham
