travis:
  secure:
    BINSTAR_TOKEN: nOqAGAPQeIVU9gznP9MRzPbTj0Yw0rIj+ayPjanm2ztYWz/l5yiTrRCwVMOJWoy78DzSEQ3YrC8H1yYRUwJj3bECWA4/W11TfliSPy0THln7HTuYzuKMzTszV4vMiK0x+PnOJG56SlxFvCdr73EMLCI5toZV/AoG/Qwq/P5qHdCWW70k7Q0/3USxnWZH7p4YPSfWDvPgVVYFrLroXeYUr3RhBb1T8KJQFGJdjY5r8qL8OkcQHXpimRYrXkIeclcWPaR6UvB0PkHLRzfTYLagxErqAW7+ZAvl1CZ2iSvEUwM+busQRQcCu/iFIWBNDOi/T2nrKBo2s0eC/2EL+ldYAb7kf8WcG4Agmo/1nyRaKbuBszHWxrFsIURxRRRy4JPnd1i7aLm6CSk7qTtCaFbi5RPA6LTXug9T8g51aCH63QSUj2sFip5Pt6aMUVbxPxtBPRmnM+Q7OI1CA1YkZaQIXTs5CBDvMHiyQiUS0huUkhpFsDG5tcuB9QFJFCRJ4uYqb0XzWyvjrFS3XhOSbAwta2asNmd+2JT7R/IR4KlHa0HHIaux3D8pJHndvP9ZbglT06vBMNXoNYux79p1r2+e/KMlLQrZZKoWbpnOPM0890y/5F+LYrmGmsfTX87jDhv+hd8DIStAwfLzcbu416hDCpPlI8hZNG9eOS9Ubd/JIwM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
