travis:
  secure:
    BINSTAR_TOKEN: xWFXwwZmP+ew3mZMrwWkFkJKJ9VBpT54C+AyuWWktwVmL/StA30Xzu2vccNra4ydZ8D05Kyhnq19J0oxjqXs6zPJ4CzPTGFJrRwbTqCOyNoLab11M2mIUDvi+WLI6iZdt0HpJQFQyTccRuwoCq8yvFChaZK0//kORlmUSCtAcqRS4bP/aeDNVbF0eRqDfYdeAS7Ie2YzcOdQyvjj5/kVTxpkjHj7phf1cF9zzdc0jKdMu6wWx7nLQUAraZYz56Uv6mrIfzfdYoD3FhOmFN9TygG+Lc+4exfVrUyXXwTQ74A5NuMV0p8Npr3NF+v0+fENvY3GTEhWzY6HgL0TDvrLni5ujeQ/KfkkI5sgWK9FPj8CMCtW3kMpym90kOwvjcR/95O+z6jBZ3YKj0mKdHTC1Q06bq1w8kz0uYrUA3sLx0oj9UGjNCo+EWLENaDiDIk6J1E7r1wPR9opC7HoAWq7gajh44xQsg9hC/MgwMFJroWmScugnsw23tUoIh44OFc0glxf7CsgBuOAMZ6a/j7HPEdDW0ANE/RGsmw4QZilTvnPBOPf/e/Mlu9i3qO3P8HAsTHMeeckHIcdJsx1QLku27Yh0HoGnML15A+HVVR9IDCZ8DkSx7ngOu7vt7xGkxvD81dOFd66wREhliFHRUJkDINSEVkpVnz4ePKC4xI/aGQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
