travis:
  secure:
    BINSTAR_TOKEN: yu2PAfMr69+nmvpZxpiJpKBBMPB0ZRImZZuXxv0RgDL3NO0zo3UGamALPeXiXd01NDatbFfpFwQpVGFl2Fm1npM72am7QY8AbJ3GC2JXhkTPCkPapSJ/Rp4R+qsPApeW4UhDU68ZspyYYsb9QKyDBmllwI2sp2Pbby6QLIO0LPDm7E/adw1E6E0QfWwxx5avc8gaFg+pkU6qL5fdyeiG/5yPygQvPCTpktqAir/LP2OIpvSXHAOQvszc33A4dVfBA6nHjmKJbdpv120Q6rJ54EDlUuyvYyGDGaw7AL5+bdgXsNG/kwRcLTkNcn94sQ6UWdFLrwgZ8E7j4vF46e6WbksdPvYBVISlAkVU8c25Lk9Y0UZ94NHoEhGD31u4WDzot7FusGha32tU0nVSG0RSzrCq7Ssli0354ONdwWEZR8ib9OFkXWQ3hpZ4onIycA5FL5tcA2HQT03y00C27fF6SGPev0VxLZVYX03iiGioz+Om5QVZ2KG5fBwIRHAGBVbgmkUqZTMl//pEzQbqyb3H2eH/Ue4AsLixw6QluM4JcH6TWrSj9LSyrSZzaA2J0etXB17e8LaGvI3o/T2yZnMJmn5gRFEVKzoDEGl4BA4SgSOvyxQetS6OqvschCGCc6d8EpD4jZL0KduP2lmq8v2aBIH4T2h/r7COHChSV3KB8ts=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
